# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 14f1aea896acb69b199851e6e5aa106544356b565500dd3b46e5fc7ce9bbdcf16dfb85c01b119f528dbb08cbf3153f065586dd00fea99a744819474485785c4e

test:
  secret_key_base: f1660fa01826f79afb8f82608b238ec08a7de5809b86457ef6bdff79c91905228cbe4e08394d095fe0aff78cc3b19858525869ac9e25ea8f6ec9ed8a28d8bbd5

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
